version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./
    environment:
      - MONGO_HOST=mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
